import { SelectOption } from "@/shared/ui";
import { TableColumn } from "@/shared/ui/Table";

export const LEAGUE_OPTIONS: SelectOption[] = [
  { value: "rpl", label: "Российская Премьер-лига" },
  { value: "epl", label: "Английская Премьер-лига" },
  { value: "laliga", label: "Испанская Ла Лига" },
  { value: "seriea", label: "Итальянская Серия А" },
  { value: "bundesliga", label: "Немецкая Бундеслига" },
  { value: "ligue1", label: "Французская Лига 1" },
  { value: "primeira", label: "Португальская Примейра" },
];

export const STANDINGS_DATA_BY_LEAGUE: Record<string, any[]> = {
  rpl: [
    {
      position: 1,
      team: "Зенит",
      matches: 20,
      wins: 15,
      draws: 3,
      losses: 2,
      goalsFor: 48,
      goalsAgainst: 18,
      points: 48,
    },
    {
      position: 2,
      team: "Краснодар",
      matches: 20,
      wins: 14,
      draws: 4,
      losses: 2,
      goalsFor: 42,
      goalsAgainst: 19,
      points: 46,
    },
    {
      position: 3,
      team: "Спартак М",
      matches: 20,
      wins: 13,
      draws: 3,
      losses: 4,
      goalsFor: 38,
      goalsAgainst: 22,
      points: 42,
    },
    {
      position: 4,
      team: "Динамо М",
      matches: 20,
      wins: 12,
      draws: 5,
      losses: 3,
      goalsFor: 41,
      goalsAgainst: 25,
      points: 41,
    },
    {
      position: 5,
      team: "Локомотив М",
      matches: 20,
      wins: 11,
      draws: 4,
      losses: 5,
      goalsFor: 35,
      goalsAgainst: 24,
      points: 37,
    },
    {
      position: 6,
      team: "ЦСКА",
      matches: 20,
      wins: 10,
      draws: 5,
      losses: 5,
      goalsFor: 32,
      goalsAgainst: 23,
      points: 35,
    },
    {
      position: 7,
      team: "Ростов",
      matches: 20,
      wins: 8,
      draws: 6,
      losses: 6,
      goalsFor: 28,
      goalsAgainst: 27,
      points: 30,
    },
    {
      position: 8,
      team: "Рубин",
      matches: 20,
      wins: 7,
      draws: 5,
      losses: 8,
      goalsFor: 22,
      goalsAgainst: 26,
      points: 26,
    },
    {
      position: 9,
      team: "Крылья Советов",
      matches: 20,
      wins: 6,
      draws: 6,
      losses: 8,
      goalsFor: 24,
      goalsAgainst: 30,
      points: 24,
    },
    {
      position: 10,
      team: "Ахмат",
      matches: 20,
      wins: 5,
      draws: 7,
      losses: 8,
      goalsFor: 21,
      goalsAgainst: 28,
      points: 22,
    },
    {
      position: 11,
      team: "Оренбург",
      matches: 20,
      wins: 5,
      draws: 5,
      losses: 10,
      goalsFor: 23,
      goalsAgainst: 35,
      points: 20,
    },
    {
      position: 12,
      team: "Урал",
      matches: 20,
      wins: 4,
      draws: 6,
      losses: 10,
      goalsFor: 19,
      goalsAgainst: 32,
      points: 18,
    },
    {
      position: 13,
      team: "Факел",
      matches: 20,
      wins: 3,
      draws: 8,
      losses: 9,
      goalsFor: 16,
      goalsAgainst: 28,
      points: 17,
    },
    {
      position: 14,
      team: "Балтика",
      matches: 20,
      wins: 3,
      draws: 5,
      losses: 12,
      goalsFor: 15,
      goalsAgainst: 36,
      points: 14,
    },
    {
      position: 15,
      team: "Сочи",
      matches: 20,
      wins: 2,
      draws: 6,
      losses: 12,
      goalsFor: 18,
      goalsAgainst: 42,
      points: 12,
    },
    {
      position: 16,
      team: "Пари НН",
      matches: 20,
      wins: 2,
      draws: 4,
      losses: 14,
      goalsFor: 14,
      goalsAgainst: 41,
      points: 10,
    },
  ],
  epl: [
    {
      position: 1,
      team: "Ливерпуль",
      matches: 28,
      wins: 20,
      draws: 7,
      losses: 1,
      goalsFor: 65,
      goalsAgainst: 26,
      points: 67,
    },
    {
      position: 2,
      team: "Арсенал",
      matches: 27,
      wins: 18,
      draws: 5,
      losses: 4,
      goalsFor: 62,
      goalsAgainst: 24,
      points: 59,
    },
    {
      position: 3,
      team: "Манчестер Сити",
      matches: 27,
      wins: 17,
      draws: 5,
      losses: 5,
      goalsFor: 55,
      goalsAgainst: 30,
      points: 56,
    },
    {
      position: 4,
      team: "Астон Вилла",
      matches: 28,
      wins: 16,
      draws: 5,
      losses: 7,
      goalsFor: 55,
      goalsAgainst: 39,
      points: 53,
    },
    {
      position: 5,
      team: "Тоттенхэм",
      matches: 27,
      wins: 15,
      draws: 5,
      losses: 7,
      goalsFor: 57,
      goalsAgainst: 38,
      points: 50,
    },
    {
      position: 6,
      team: "Манчестер Юнайтед",
      matches: 27,
      wins: 14,
      draws: 2,
      losses: 11,
      goalsFor: 37,
      goalsAgainst: 38,
      points: 44,
    },
    {
      position: 7,
      team: "Вест Хэм",
      matches: 28,
      wins: 12,
      draws: 6,
      losses: 10,
      goalsFor: 42,
      goalsAgainst: 48,
      points: 42,
    },
    {
      position: 8,
      team: "Ньюкасл",
      matches: 27,
      wins: 12,
      draws: 4,
      losses: 11,
      goalsFor: 57,
      goalsAgainst: 45,
      points: 40,
    },
    {
      position: 9,
      team: "Брайтон",
      matches: 27,
      wins: 10,
      draws: 9,
      losses: 8,
      goalsFor: 47,
      goalsAgainst: 44,
      points: 39,
    },
    {
      position: 10,
      team: "Челси",
      matches: 27,
      wins: 10,
      draws: 6,
      losses: 11,
      goalsFor: 44,
      goalsAgainst: 44,
      points: 36,
    },
  ],
  laliga: [
    {
      position: 1,
      team: "Реал Мадрид",
      matches: 26,
      wins: 20,
      draws: 5,
      losses: 1,
      goalsFor: 55,
      goalsAgainst: 18,
      points: 65,
    },
    {
      position: 2,
      team: "Жирона",
      matches: 26,
      wins: 18,
      draws: 5,
      losses: 3,
      goalsFor: 55,
      goalsAgainst: 32,
      points: 59,
    },
    {
      position: 3,
      team: "Барселона",
      matches: 26,
      wins: 17,
      draws: 6,
      losses: 3,
      goalsFor: 56,
      goalsAgainst: 34,
      points: 57,
    },
    {
      position: 4,
      team: "Атлетико Мадрид",
      matches: 26,
      wins: 16,
      draws: 4,
      losses: 6,
      goalsFor: 51,
      goalsAgainst: 28,
      points: 52,
    },
    {
      position: 5,
      team: "Атлетик Бильбао",
      matches: 26,
      wins: 13,
      draws: 8,
      losses: 5,
      goalsFor: 44,
      goalsAgainst: 27,
      points: 47,
    },
    {
      position: 6,
      team: "Реал Сосьедад",
      matches: 26,
      wins: 10,
      draws: 10,
      losses: 6,
      goalsFor: 37,
      goalsAgainst: 27,
      points: 40,
    },
    {
      position: 7,
      team: "Бетис",
      matches: 26,
      wins: 9,
      draws: 12,
      losses: 5,
      goalsFor: 30,
      goalsAgainst: 26,
      points: 39,
    },
    {
      position: 8,
      team: "Валенсия",
      matches: 26,
      wins: 10,
      draws: 7,
      losses: 9,
      goalsFor: 30,
      goalsAgainst: 30,
      points: 37,
    },
  ],
  seriea: [
    {
      position: 1,
      team: "Интер",
      matches: 27,
      wins: 23,
      draws: 3,
      losses: 1,
      goalsFor: 67,
      goalsAgainst: 12,
      points: 72,
    },
    {
      position: 2,
      team: "Ювентус",
      matches: 27,
      wins: 17,
      draws: 6,
      losses: 4,
      goalsFor: 44,
      goalsAgainst: 23,
      points: 57,
    },
    {
      position: 3,
      team: "Милан",
      matches: 27,
      wins: 17,
      draws: 5,
      losses: 5,
      goalsFor: 50,
      goalsAgainst: 32,
      points: 56,
    },
    {
      position: 4,
      team: "Болонья",
      matches: 27,
      wins: 14,
      draws: 9,
      losses: 4,
      goalsFor: 41,
      goalsAgainst: 24,
      points: 51,
    },
    {
      position: 5,
      team: "Рома",
      matches: 27,
      wins: 14,
      draws: 5,
      losses: 8,
      goalsFor: 49,
      goalsAgainst: 33,
      points: 47,
    },
    {
      position: 6,
      team: "Аталанта",
      matches: 27,
      wins: 14,
      draws: 4,
      losses: 9,
      goalsFor: 49,
      goalsAgainst: 32,
      points: 46,
    },
    {
      position: 7,
      team: "Наполи",
      matches: 27,
      wins: 12,
      draws: 8,
      losses: 7,
      goalsFor: 42,
      goalsAgainst: 32,
      points: 44,
    },
    {
      position: 8,
      team: "Лацио",
      matches: 27,
      wins: 12,
      draws: 4,
      losses: 11,
      goalsFor: 32,
      goalsAgainst: 30,
      points: 40,
    },
  ],
  bundesliga: [
    {
      position: 1,
      team: "Байер 04",
      matches: 24,
      wins: 20,
      draws: 4,
      losses: 0,
      goalsFor: 61,
      goalsAgainst: 16,
      points: 64,
    },
    {
      position: 2,
      team: "Бавария",
      matches: 24,
      wins: 17,
      draws: 3,
      losses: 4,
      goalsFor: 63,
      goalsAgainst: 31,
      points: 54,
    },
    {
      position: 3,
      team: "Штутгарт",
      matches: 24,
      wins: 16,
      draws: 2,
      losses: 6,
      goalsFor: 55,
      goalsAgainst: 31,
      points: 50,
    },
    {
      position: 4,
      team: "Боруссия Д",
      matches: 24,
      wins: 12,
      draws: 8,
      losses: 4,
      goalsFor: 48,
      goalsAgainst: 32,
      points: 44,
    },
    {
      position: 5,
      team: "РБ Лейпциг",
      matches: 24,
      wins: 13,
      draws: 4,
      losses: 7,
      goalsFor: 53,
      goalsAgainst: 34,
      points: 43,
    },
    {
      position: 6,
      team: "Айнтрахт",
      matches: 24,
      wins: 9,
      draws: 9,
      losses: 6,
      goalsFor: 38,
      goalsAgainst: 34,
      points: 36,
    },
    {
      position: 7,
      team: "Хоффенхайм",
      matches: 24,
      wins: 9,
      draws: 6,
      losses: 9,
      goalsFor: 42,
      goalsAgainst: 44,
      points: 33,
    },
  ],
  ligue1: [
    {
      position: 1,
      team: "ПСЖ",
      matches: 25,
      wins: 16,
      draws: 8,
      losses: 1,
      goalsFor: 56,
      goalsAgainst: 22,
      points: 56,
    },
    {
      position: 2,
      team: "Брест",
      matches: 25,
      wins: 13,
      draws: 7,
      losses: 5,
      goalsFor: 36,
      goalsAgainst: 22,
      points: 46,
    },
    {
      position: 3,
      team: "Монако",
      matches: 25,
      wins: 13,
      draws: 6,
      losses: 6,
      goalsFor: 46,
      goalsAgainst: 34,
      points: 45,
    },
    {
      position: 4,
      team: "Лилль",
      matches: 25,
      wins: 11,
      draws: 9,
      losses: 5,
      goalsFor: 37,
      goalsAgainst: 22,
      points: 42,
    },
    {
      position: 5,
      team: "Ницца",
      matches: 25,
      wins: 11,
      draws: 7,
      losses: 7,
      goalsFor: 25,
      goalsAgainst: 21,
      points: 40,
    },
    {
      position: 6,
      team: "Ланс",
      matches: 25,
      wins: 10,
      draws: 6,
      losses: 9,
      goalsFor: 32,
      goalsAgainst: 29,
      points: 36,
    },
  ],
  primeira: [
    {
      position: 1,
      team: "Спортинг",
      matches: 24,
      wins: 20,
      draws: 2,
      losses: 2,
      goalsFor: 66,
      goalsAgainst: 24,
      points: 62,
    },
    {
      position: 2,
      team: "Бенфика",
      matches: 24,
      wins: 18,
      draws: 4,
      losses: 2,
      goalsFor: 55,
      goalsAgainst: 20,
      points: 58,
    },
    {
      position: 3,
      team: "Порту",
      matches: 24,
      wins: 16,
      draws: 4,
      losses: 4,
      goalsFor: 43,
      goalsAgainst: 19,
      points: 52,
    },
    {
      position: 4,
      team: "Брага",
      matches: 24,
      wins: 13,
      draws: 5,
      losses: 6,
      goalsFor: 45,
      goalsAgainst: 34,
      points: 44,
    },
    {
      position: 5,
      team: "Витория Гимарайнш",
      matches: 24,
      wins: 12,
      draws: 5,
      losses: 7,
      goalsFor: 37,
      goalsAgainst: 28,
      points: 41,
    },
    {
      position: 6,
      team: "Морейренсе",
      matches: 24,
      wins: 11,
      draws: 6,
      losses: 7,
      goalsFor: 29,
      goalsAgainst: 26,
      points: 39,
    },
  ],
};

export const STANDINGS_COLUMNS: TableColumn[] = [
  { key: "position", label: "№", align: "center", width: "50px" },
  { key: "team", label: "Команда", align: "left" },
  { key: "matches", label: "И", align: "center", width: "50px" },
  { key: "wins", label: "В", align: "center", width: "50px" },
  { key: "draws", label: "Н", align: "center", width: "50px" },
  { key: "losses", label: "П", align: "center", width: "50px" },
  { key: "goalsFor", label: "З", align: "center", width: "50px" },
  { key: "goalsAgainst", label: "П", align: "center", width: "50px" },
  { key: "points", label: "О", align: "center", width: "60px" },
];
