export const BONUSES_DATA = [
  {
    id: "1xbet",
    logo: "/images/bonuses/1xbet-logo.png",
    title: "Бонус 120% до",
    amount: "400 $",
    subtitle: "на первый депозит",
    bonusAmount: "400 $",
    minOdds: "1.40",
    wagering: "5",
    buttonText: "Получить бонус",
    terms: `Зарегистрируйся на 1xBet и пополни счет от 2 USD. Получи до 400 USD бонуса, который нужно отыграть в экспрессах с коэффициентом не ниже 1.40 в течение 30 дней.`,
  },
  {
    id: "1xbet",
    logo: "/images/bonuses/1xbet-logo.png",
    title: "Бонус 120% до",
    amount: "400 $",
    subtitle: "на первый депозит",
    bonusAmount: "400 $",
    minOdds: "1.40",
    wagering: "5",
    buttonText: "Получить бонус",
    terms: `Зарегистрируйся на 1xBet и пополни счет от 2 USD. Получи до 400 USD бонуса, который нужно отыграть в экспрессах с коэффициентом не ниже 1.40 в течение 30 дней.`,
  },
  {
    id: "1xbet",
    logo: "/images/bonuses/1xbet-logo.png",
    title: "Бонус 120% до",
    amount: "400 $",
    subtitle: "на первый депозит",
    bonusAmount: "400 $",
    minOdds: "1.40",
    wagering: "5",
    buttonText: "Получить бонус",
    terms: `Зарегистрируйся на 1xBet и пополни счет от 2 USD. Получи до 400 USD бонуса, который нужно отыграть в экспрессах с коэффициентом не ниже 1.40 в течение 30 дней.`,
  },
];
