export const FEATURED_MATCHES = [
  {
    id: 1,
    homeTeam: "Арсенал",
    awayTeam: "Челси",
    time: "19:30",
    date: "22.03.2026",
    tournament: "Английская Премьер-лига",
  },
  {
    id: 2,
    homeTeam: "Динамо М",
    awayTeam: "Спартак М",
    time: "16:00",
    date: "22.03.2026",
    tournament: "Российская Премьер-лига",
  },
  {
    id: 3,
    homeTeam: "Крылья Советов",
    awayTeam: "ЦСКА",
    time: "16:30",
    date: "22.03.2026",
    tournament: "Российская Премьер-лига",
  },
  {
    id: 4,
    homeTeam: "Локомотив М",
    awayTeam: "Краснодар",
    time: "19:00",
    date: "22.03.2026",
    tournament: "Российская Премьер-лига",
  },
  {
    id: 5,
    homeTeam: "Тоттенхэм",
    awayTeam: "Ливерпуль",
    time: "17:15",
    date: "22.03.2026",
    tournament: "Английская Премьер-лига",
  },
  {
    id: 6,
    homeTeam: "Астон Вилла",
    awayTeam: "Манчестер Юнайтед",
    time: "17:15",
    date: "22.03.2026",
    tournament: "Английская Премьер-лига",
  },
  {
    id: 7,
    homeTeam: "Манчестер Сити",
    awayTeam: "Ньюкасл",
    time: "19:30",
    date: "22.03.2026",
    tournament: "Кубок Англии",
  },
  {
    id: 8,
    homeTeam: "Зенит",
    awayTeam: "Ростов",
    time: "16:00",
    date: "22.03.2026",
    tournament: "Российская Премьер-лига",
  },
  {
    id: 9,
    homeTeam: "Рубин",
    awayTeam: "Ахмат",
    time: "16:30",
    date: "22.03.2026",
    tournament: "Российская Премьер-лига",
  },
  {
    id: 10,
    homeTeam: "Акрон Тольятти",
    awayTeam: "Оренбург",
    time: "19:00",
    date: "22.03.2026",
    tournament: "Российская Премьер-лига",
  },
  {
    id: 11,
    homeTeam: "Ноттингем Форест",
    awayTeam: "Брайтон",
    time: "17:15",
    date: "22.03.2026",
    tournament: "Английская Премьер-лига",
  },
  {
    id: 12,
    homeTeam: "Вест Хэм",
    awayTeam: "Брентфорд",
    time: "17:15",
    date: "22.03.2026",
    tournament: "Английская Премьер-лига",
  },
];
